import { Link } from "react-router";

const tech = ["Next.js", "TypeScript", "PostgreSQL", "Prisma", "tRPC", "Vercel"];
const gallery = [
  ["Desktop workspace", "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&h=1040&fit=crop&auto=format"],
  ["Responsive review", "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1300&h=900&fit=crop&auto=format"],
  ["Reporting detail", "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1300&h=900&fit=crop&auto=format"],
] as const;

function Mark() { return <span className="grid size-6 place-items-center rounded-[7px] bg-ink text-xs font-bold text-background">A</span>; }
function CaseHeading({ number, title, text }: {number:string; title:string; text?:string}) { return <div className="lg:sticky lg:top-28"><p className="font-mono text-[10px] tracking-[.16em] text-brand">{number}</p><h2 className="mt-4 text-2xl font-semibold tracking-[-.045em] sm:text-3xl">{title}</h2>{text && <p className="mt-3 max-w-xs text-sm leading-6 text-muted">{text}</p>}</div> }

export default function ProjectDetail() {
 return <main className="min-h-screen bg-background text-ink antialiased">
  <header className="sticky top-0 z-50 border-b border-line bg-background/95 backdrop-blur-sm"><div className="mx-auto flex h-16 max-w-[1200px] items-center justify-between px-6 sm:px-8 lg:px-10"><Link to="/" className="flex items-center gap-2 text-sm font-semibold tracking-[-.02em]"><Mark /> ARUN.DEV</Link><div className="flex items-center gap-4 text-sm"><Link to="/#projects" className="text-muted transition hover:text-ink">All projects</Link><a href="#contact" className="rounded-lg border border-line px-3.5 py-2 font-medium transition hover:bg-card">Let's talk <span className="text-muted">↗</span></a></div></div></header>
  <section className="border-b border-line"><div className="mx-auto max-w-[1200px] px-6 py-16 sm:px-8 lg:px-10 lg:py-24"><Link to="/#projects" className="inline-flex items-center gap-2 font-mono text-[10px] tracking-[.14em] text-muted transition hover:text-ink">← BACK TO SELECTED WORK</Link><div className="mt-12 grid gap-12 lg:grid-cols-[1.25fr_.75fr] lg:items-end"><div><div className="flex items-center gap-2 font-mono text-[10px] tracking-[.15em] text-brand"><span className="size-1.5 rounded-full bg-brand"/> CASE STUDY / 2025</div><h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[.98] tracking-[-.065em] sm:text-7xl">Making financial decisions feel less overwhelming.</h1></div><p className="max-w-md text-[15px] leading-7 text-muted">Relay Finance is a focused planning workspace for independent teams that need to turn live financial data into clear next steps.</p></div><div className="mt-16 grid border-l border-t border-line sm:grid-cols-4">{[["ROLE","Product & engineering"],["TIMELINE","14 weeks"],["TEAM","3 people"],["STATUS","Shipped"]].map(([a,b])=><div key={a} className="border-r border-b border-line px-4 py-4"><p className="font-mono text-[9px] tracking-[.13em] text-muted">{a}</p><p className="mt-2 text-xs text-zinc-300">{b}</p></div>)}</div></div></section>
  <section className="mx-auto max-w-[1200px] px-6 py-10 sm:px-8 lg:px-10"><div className="overflow-hidden rounded-panel border border-line bg-card"><div className="flex h-10 items-center gap-1.5 border-b border-line px-4"><span className="size-2 rounded-full bg-zinc-700"/><span className="size-2 rounded-full bg-zinc-700"/><span className="size-2 rounded-full bg-zinc-700"/><span className="ml-3 font-mono text-[9px] tracking-[.12em] text-zinc-500">APP.RELAYFINANCE.COM</span></div><img className="aspect-[2/1] w-full object-cover opacity-85" src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1800&h=900&fit=crop&auto=format" alt="Relay Finance dashboard overview" /></div></section>
  <section className="mx-auto max-w-[1200px] px-6 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-10 border-b border-line pb-20 lg:grid-cols-[.7fr_1.3fr]"><CaseHeading number="01 / OVERVIEW" title="A decision engine, not another dashboard." text="The work began by questioning what financial software should optimize for."/><div className="max-w-2xl"><p className="text-xl leading-8 tracking-[-.025em] text-zinc-300">Relay turns accounts, obligations, and forecasts into a steady, practical operating rhythm for small teams.</p><p className="mt-5 text-[15px] leading-7 text-muted">Instead of asking people to interpret a wall of financial widgets, we designed a product around the questions that recur every week: What changed? What needs attention? What can we confidently decide now?</p><div className="mt-9 flex flex-wrap gap-2">{tech.map(t=><span key={t} className="rounded-md border border-line bg-surface px-2.5 py-1.5 font-mono text-[10px] text-zinc-400">{t}</span>)}</div></div></div></section>
  <section className="border-y border-line bg-surface"><div className="mx-auto max-w-[1200px] px-6 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><CaseHeading number="02 / PROBLEM & SOLUTION" title="Clarity was the feature."/><div className="grid gap-8 md:grid-cols-2"><div className="rounded-panel border border-line bg-background p-6"><p className="font-mono text-[10px] tracking-[.14em] text-muted">THE PROBLEM</p><h3 className="mt-4 text-lg font-semibold tracking-[-.03em]">Signal was buried under reporting.</h3><p className="mt-3 text-sm leading-6 text-muted">Teams had data across banking, payroll, and revenue tools but no concise picture of cash health or upcoming constraints.</p></div><div className="rounded-panel border border-line bg-background p-6"><p className="font-mono text-[10px] tracking-[.14em] text-brand">THE SOLUTION</p><h3 className="mt-4 text-lg font-semibold tracking-[-.03em]">A weekly financial briefing.</h3><p className="mt-3 text-sm leading-6 text-muted">We distilled activity into an intentional review flow: movement, forecast, decisions, and supporting detail only when needed.</p></div></div></div></div></section>
  <section className="mx-auto max-w-[1200px] px-6 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><CaseHeading number="03 / FEATURES" title="Less interface. Better judgment."/><div className="divide-y divide-line border-y border-line">{[["Weekly briefing","A concise summary of movement, forecast, and the decisions that deserve attention."],["Scenario planning","A clear way to model the impact of hiring, expenditure, or changed revenue assumptions."],["Traceable forecasts","Every forecast makes its inputs visible, so confidence has an understandable source."]].map(([title,text],i)=><div className="grid gap-3 py-6 sm:grid-cols-[48px_1fr]" key={title}><span className="font-mono text-xs text-brand">0{i+1}</span><div><h3 className="text-base font-medium">{title}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-muted">{text}</p></div></div>)}</div></div></section>
  <section className="border-y border-line bg-surface"><div className="mx-auto max-w-[1200px] px-6 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="flex flex-col justify-between gap-6 border-b border-line pb-8 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] tracking-[.16em] text-brand">04 / GALLERY</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.045em]">Designed for every review.</h2></div><p className="max-w-sm text-sm leading-6 text-muted">A responsive product system that stays composed from an operating desk to a quick mobile check-in.</p></div><div className="mt-8 grid gap-5 lg:grid-cols-2">{gallery.map(([label,img],i)=><figure key={label} className={i===0?"lg:col-span-2":""}><div className="overflow-hidden rounded-panel border border-line bg-card"><img src={img} alt={label} className={`w-full object-cover opacity-75 transition duration-500 hover:scale-[1.02] ${i===0?"aspect-[2.1/1]":"aspect-[1.35/1]"}`}/></div><figcaption className="mt-3 font-mono text-[10px] tracking-[.13em] text-muted">{String(i+1).padStart(2,"0")} / {label.toUpperCase()}</figcaption></figure>)}</div></div></section>
  <section className="mx-auto max-w-[1200px] px-6 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><CaseHeading number="05 / ARCHITECTURE" title="Fast by default, robust by design."/><div className="rounded-panel border border-line bg-surface p-5 sm:p-7"><div className="font-mono text-[10px] leading-7 text-zinc-400"><p className="text-brand">CLIENT</p><p className="border-l border-line pl-5">Next.js App Router <span className="text-zinc-600">→</span> Server Components</p><p className="border-l border-line pl-5">tRPC <span className="text-zinc-600">→</span> typed service boundary</p><p className="mt-3 text-brand-blue">DATA</p><p className="border-l border-line pl-5">PostgreSQL <span className="text-zinc-600">→</span> Prisma ORM</p><p className="border-l border-line pl-5">Plaid sync <span className="text-zinc-600">→</span> queue-backed ingestion</p><p className="mt-3 text-green-400">DELIVERY</p><p className="border-l border-line pl-5">Vercel Edge <span className="text-zinc-600">→</span> preview-first workflow</p></div><p className="mt-6 border-t border-line pt-5 text-sm leading-6 text-muted">The architecture keeps computation close to the data source, while lightweight client components preserve the immediacy of the product's review loop.</p></div></div></section>
  <section className="border-t border-line bg-surface"><div className="mx-auto max-w-[1200px] px-6 py-20 sm:px-8 lg:px-10 lg:py-28"><div className="grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><CaseHeading number="06 / LEARNINGS" title="A calm product is an active decision."/><div><p className="text-xl leading-8 tracking-[-.025em] text-zinc-300">The best measure of success wasn't how long people stayed in Relay—it was how confidently they could leave it.</p><div className="mt-8 grid gap-4 sm:grid-cols-2"><div className="rounded-panel border border-line bg-background p-5"><p className="font-mono text-[10px] tracking-[.14em] text-muted">CHALLENGE</p><p className="mt-3 text-sm leading-6 text-zinc-300">Forecasts had to be transparent enough to build trust without making every assumption a burden.</p></div><div className="rounded-panel border border-line bg-background p-5"><p className="font-mono text-[10px] tracking-[.14em] text-brand">LESSON</p><p className="mt-3 text-sm leading-6 text-zinc-300">When a workflow is high-stakes, restraint is not aesthetic—it is functional.</p></div></div></div></div><div id="contact" className="mt-20 flex flex-col items-start justify-between gap-6 border-t border-line pt-8 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] tracking-[.15em] text-muted">NEXT PROJECT</p><h2 className="mt-3 text-2xl font-semibold tracking-[-.04em]">Atlas Health</h2></div><Link to="/" className="rounded-[10px] bg-ink px-4 py-3 text-sm font-semibold text-background transition hover:-translate-y-0.5">Back to portfolio <span className="ml-1">↗</span></Link></div></div></section>
  <footer className="border-t border-line"><div className="mx-auto flex max-w-[1200px] justify-between px-6 py-7 text-xs text-muted sm:px-8 lg:px-10"><span>© 2026 ARUN.DEV</span><Link to="/" className="hover:text-ink">Home ↑</Link></div></footer>
 </main>;
}
